she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), #bringing up the IndexView class on viewspy
    path('<int:pk>/', views.StoryView.as_view(), name='story'), #directing us to the  number of a specific story (integer primary key) AND 
    path('add-story/', views.AddStoryView.as_view(), name='newStory')
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from . import views
from .views import CreateAccountView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model

class NewsStory(models.Model):
    class Meta:
        ordering = ['-pub_date']
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.URLField(blank=True)

    def get_absolute_url(self):
        return reverse('news:story', kwargs={'pk': self.pk})

she_codes_news/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    image_url = models.URLField(blank=True)
    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('news:story', kwargs={'pk': self.pk})

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content','image_url']
        widgets = {
        'pub_date': forms.DateInput(format=('%m/%d/%Y'),
        attrs={'class':'form-control',
        'placeholder':'Select a date',
        'type':'date'}),
        
}

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(help_text='Required*')
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254, help_text='Valid email address required*')
    image_url = forms.URLField(help_text='Valid URL required*', required=True)

    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'image_url', 'password1', 'password2']

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'image_url']
        

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm

class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all()[:4]
        context['all_stories'] = NewsStory.objects.all()
        # ----- Another way to re-order stories by date ----- # context['old_stories'] = NewsStory.objects.all().order_by('pub_date')[:4]
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm


class CreateAccountView(CreateView):
	form_class = CustomUserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'users/createAccount.html'

class UserProfileView(generic.DetailView):
    model = CustomUser
    template_name = 'users/userProfileHome.html'
    context_object_name = 'profile'

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}


{% block content %}

<div id="add-story">
    {% if user.is_authenticated %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>
    {% else %}
        <p>You are not logged in.</p>
        <a href="{% url 'login' %}">Login or</a> <a href="{% url 'users:createAccount' %}">Create Account</a> 
    {% endif %}  
</div>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
    {% if request.user.is_authenticated %}
        <a href="{% url 'news:newStory' %}">Write New Story</a>
    {% else %}
        <p>Want to write a story?</p>
        <a href="{% url 'login' %}">Login or</a> <a href="{% url 'users:createAccount' %}">Create Account</a> 

    {% endif %}
{% endblock %}

{% block content %}

    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <h2>All Stories</h2>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>Story by: {{ story.author }}. <a href="{% url 'users:profile' story.author.id %}"> (View {{ story.author }}'s profile) </a> </h4> 
    <div id="story-content">
        {% if story.image_url %}
            <img src="{{ story.image_url }}">
        {% else %}
        <img src="https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2F0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=1296&q=60">
        {% endif %}
    {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if story.image_url %}
            <img src="{{ story.image_url }}"">
        {% else %}
            <img src="https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2F0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=1296&q=60">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
            {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
    {% block content %}
    {% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    {% if request.user.is_authenticated %}
    <a href="{% url 'users:profile' request.user.id %}">Logged in as {{ request.user.username }}. View account </a>
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:createAccount' %}">Create Account</a>
    {% endif %}
    

</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Account</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Create Account</button>
</form>
{% endblock %}

she_codes_news/users/templates/users/userProfileHome.html
{% extends 'base.html' %}

{% block content %}
<h2>Username: {{ profile.username }}</h2>

{% if profile.image_url %}
    <img src="{{ profile.image_url }}" width="300">
{% else %}
    <img src="https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2F0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=1296&q=60" width="300">
{% endif %}

<p>First name: {{ profile.first_name }}</p>
<p>Last name: {{ profile.last_name }}</p>

<!-- Showing all of the posts written by a specific user -->

<p></p>
<h2> All stories by {{ profile.username }}</h2>


{% for story in profile.newsstory_set.all %}
    {% include "news/storyCard.html" with story=story %}
{% endfor %}


{% endblock %}